### ISSUE TITLE
Cert error on Nimbus6

### ISSUE THREAD

**Issue by sashakames** [esgf-nimbus/nimbus#1]
Browsers give the following errors
Firefox:
Secure Connection Failed

An error occurred during a connection to nimbus6.llnl.gov. Certificate key usage inadequate for attempted operation.

Error code: SEC_ERROR_INADEQUATE_KEY_USAGE
Chrome:
NET::ERR_CERT_AUTHORITY_INVALID
Subject: nimbus6.llnl.gov

Issuer: nimbus6.llnl.gov

Strange that they are not consistent, looks like a self-signed cert so maybe LetsEncrypt failed?

**Comment by jasonb5** [comment]
@sashakames Closing this as it's been resolved.
