### ISSUE TITLE
[BUG] xcdat has ESMF dependency that fails

### ISSUE THREAD

**Issue by durack1** [esgf-nimbus/nimbus#18]
**Describe the bug**
Attempting to import `xcdat` on Nimbus currently returns an error associated with ESMF.

**To Reproduce**
1. Open a "Climate notebook"
2. Create a new notebook
3. Attempt to import xcdat `import xcdat as xc`

**Expected behavior**
This should launch, but instead returns an error:
```
import xcdat as xc

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/esmpy/interface/loadESMF.py", line 154, in <module>
    _ESMF = ct.CDLL(os.path.join(libsdir,'libesmf_fullylinked.so'),
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Screenshots**
see above

**Desktop (please complete the following information):**
Nimbus jupyterhub env - current "Climate notebook" env

**Additional context**
A similar issue occurred in the past https://github.com/esgf-nimbus/nimbus/issues/15, but the error this time is different

**Comment by durack1** [comment]
It seems like this issue also impacts `xarray`, so effectively jupyterlab is not working at all on nimbus at the moment

```python
import xarray as xr
ds = xr.open_mfdataset("".join([filePath, "*"]))
```
yields
```python
ImportError: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by mbarcodia** [comment]
When trying to import xcdat, I encounter the following error, which prohibits me from opening files. 
In the "minimal notebook" I get:
<img width="642" alt="Screenshot 2024-06-18 at 12 24 23 PM" src="https://github.com/esgf-nimbus/nimbus/assets/115642813/e2dca9d0-c42d-43d0-a9e2-c87c6a6360eb">

With the climate notebook, I get an error saying "no module named ESMF":
![image (1)](https://github.com/esgf-nimbus/nimbus/assets/115642813/dab46e51-9a35-4f9b-b709-743579effdc8)
![image](https://github.com/esgf-nimbus/nimbus/assets/115642813/6a1e9732-a7b3-4b00-be1e-3d2e3153f928)

**Comment by jasonb5** [comment]
@durack1 Thanks for reporting, now that everything is sorted out I will start looking at this today.
@mbarcodia Thanks for the details, I'll have an update soon.

**Comment by jasonb5** [comment]
@durack1 @mbarcodia It looks like that library was being deleted on the host systems which propagated to the JupyterHub instances. I'm resolving this with the machine maintainer and will have an update soon.

**Comment by jasonb5** [comment]
@durack1 @mbarcodia Go ahead and try the "Climate Environment" again.

**Comment by durack1** [comment]
@jasonb5 perfect, works for me - @mbarcodia did you want to check to make sure it's fixed for you too?

**Comment by mbarcodia** [comment]
It worked for me too! @Paul, I am running the full querySosData.ipynb
notebook without issue.

Thank you both for your help!
-Marybeth

----------------------------------------
*Marybeth C. Arcodia, Ph.D.*  | she/her
Research Scientist
Dept of Atmospheric Science
Colorado State University
Email: ***@***.***
Website: marybetharcodia.wixsite.com/earth
