### ISSUE TITLE
[BUG] spawn failure

### ISSUE THREAD

**Issue by znichollscr** [esgf-nimbus/nimbus#20]
**Describe the bug**

**To Reproduce**
1. Go to https://nimbus.llnl.gov/
2. Login as me "znichollscr"

**Expected behavior**
Successful login

**Screenshots**
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/a8db347e-218e-4fba-a059-c869fa5890d8">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Brave
 - Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (arm64)

**Additional context**

**Comment by sashakames** [comment]
Looks like this was an intermittent issue.  I just spawned an NB no problem..

**Comment by znichollscr** [comment]
Unfortunately not for me. I'm still getting the same error message. Unlike #21, it seems that my spawner is trying to kill some other process and failing so I think I'm in a different broken state to the issue in #21. @jasonb5 you helped @durack1 , are you the right person to ask?

**Comment by durack1** [comment]
@znichollscr can you capture the error here? It would be more useful for diagnostics.

Another check, if you point your browser at https://nimbus.llnl.gov/hub/home, can you select "Stop My Server", that might get you killed, and a restart will work

**Comment by znichollscr** [comment]
Same error as in the original issue description:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/81d0096b-78e8-433e-9776-1e6c05d01ea2">



> Another check, if you point your browser at [nimbus.llnl.gov/hub/home](https://nimbus.llnl.gov/hub/home), can you select "Stop My Server", that might get you killed, and a restart will work

Appears not possible unfortunately

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/7f636e86-cdd7-4874-9c19-bfbdd7376fb8">

**Comment by angrydonkey5** [comment]
@durack1 @znichollscr Try to access the instance again, this issue should be resolved. Thanks!

**Comment by jasonb5** [comment]
@durack1 @znichollscr This issue should be resolved, try your instance again.

**Comment by znichollscr** [comment]
Thank you, issue resolved
