### ISSUE TITLE
[BUG] Spawn failure

### ISSUE THREAD

**Issue by durack1** [esgf-nimbus/nimbus#21]
**Describe the bug**
Upon attempting to start a jupyterhub instance this am, it failed

**To Reproduce**
1. Login to https://nimbus.llnl.gov
2. Select "climate notebook"
3. Awaiting to load..

**Expected behavior**
This should have loaded

**Screenshots**
![Screenshot 2024-10-16 at 7 18 15 AM](https://github.com/user-attachments/assets/0a3c6178-d3c5-4fa4-8ee2-68331af9363a)

**Desktop (please complete the following information):**
 - OS: macOS 14.7
 - Browser: Firefox 128.3.1esr

**Additional context**
I hope this is an easy fix!

ping @znichollscr @sashakames @jasonb5

**Comment by jasonb5** [comment]
@durack1 Can you try it again. Thanks!

**Comment by durack1** [comment]
@jasonb5 I'm back up and running, great, thanks!
